import {
  Sparkles,
  Users,
  Wallet,
  Database,
  Boxes,
  FileBarChart2,
  Settings,
  SquareTerminal,
  PackageCheck,
  HardDriveUpload,
  HardDriveDownload,
  Computer,
  Contact,
} from "lucide-react";
import type { SidebarData } from "@/lib/sidebar";

export const sidebarData: SidebarData = {
  user: {
    name: "error",
    email: "error@error.com",
    avatar: "/avatars/shadcn.jpg",
  },
  navMain: [
    { title: "Dashboard", url: "/dashboard", icon: SquareTerminal },
    { title: "Tanya AI", url: "#", icon: Sparkles },
    { title: "Produk", url: "#", icon: PackageCheck },
    {
      title: "Kontak",
      url: "#",
      icon: Users,
      items: [
        { title: "Pelanggan", url: "#" },
        { title: "Pemasok", url: "#" },
        { title: "Karyawan", url: "#" },
        { title: "Kategori Kontak", url: "#" },
      ],
    },
    { title: "Penjualan", url: "#", icon: HardDriveUpload },
    { title: "Pembelian", url: "#", icon: HardDriveDownload },
    {
      title: "Keuangan",
      url: "#",
      icon: Wallet,
      items: [
        { title: "Pengeluaran", url: "#" },
        { title: "Pemasukan", url: "#" },
        { title: "Transfer Kas/Bank", url: "#" },
        { title: "Hutang", url: "#" },
        { title: "Piutang", url: "#" },
        { title: "Kategoti Pengeluaran", url: "#" },
        { title: "Akun Keuangan", url: "#" },
        { title: "Manual Jurnal", url: "#" },
        { title: "Pengecekan", url: "#" },
      ],
    },
    {
      title: "Kasir",
      url: "#",
      icon: Computer,
      items: [
        { title: "Akses", url: "#" },
        { title: "Metode Pembayaran", url: "#" },
        { title: "Mode Kasir", url: "#" },
        { title: "Laporan Shift", url: "#" },
        { title: "Cetak Label Harga", url: "#" },
        { title: "Laporan Kasir", url: "#" },
        { title: "Pengaturan Print", url: "#" },
        { title: "Pengaturan Kasir", url: "#" },
      ],
    },
    {
      title: "Data Master",
      url: "#",
      icon: Database,
      items: [
        { title: "Proyek", url: "#" },
        { title: "Kategori Produk", url: "#" },
        { title: "Outlet / Gudang", url: "#" },
        { title: "Satuan", url: "#" },
        { title: "Konversi Satuan", url: "#" },
        { title: "Diskon", url: "#" },
        { title: "Pajak", url: "#" },
        { title: "Harga Ojek Online", url: "#" },
        { title: "File", url: "#" },
      ],
    },
    {
      title: "Persediaan",
      url: "#",
      icon: Boxes,
      items: [
        { title: "Stok Produk", url: "#" },
        { title: "Penyesuaian Stok", url: "#" },
        { title: "Pindah Gudang", url: "#" },
      ],
    },
    {
      title: "CRM",
      url: "#",
      icon: Contact,
      items: [
        { title: "Progam Loyalitas", url: "#" },
        { title: "Tingkatan Pelanggan", url: "#" },
        { title: "Point Pelanggan", url: "#" },
        { title: "Riwayat Poin", url: "#" },
      ],
    },
    {
      title: "Laporan",
      url: "#",
      icon: FileBarChart2,
      items: [
        { title: "Laba Rugi", url: "#" },
        { title: "Neraca", url: "#" },
        { title: "Laporan Penjualan", url: "#" },
        { title: "Penjualan Item", url: "#" },
        { title: "Penjualan Produk", url: "#" },
        { title: "Penjualab Pelanggan", url: "#" },
        { title: "Pengeluaran Kontak", url: "#" },
        { title: "HPP Produk", url: "#" },
        { title: "Riwayat Jurnal", url: "#" },
      ],
    },
    { title: "Pengaturan", url: "#", icon: Settings },
  ],
};
