import { Metadata } from "next";
import BarChartSales from "./BarChartSales";
import LineChartSales from "./LineChartSales";
import RecentSales from "./RecentSales";
import Auth from "@/components/auth";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

function DashboardPage() {
  return (
    <div className="p-4 h-full">
      <Auth />
      <h1 className="text-xl">Dashboard</h1>
      <div className="mt-4">
        <BarChartSales />
      </div>
      <div className="mt-4 sm:flex gap-4">
        <LineChartSales />
        <RecentSales />
      </div>
    </div>
  );
}

export default DashboardPage;
